Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from osipi_dce_dsc_repo.wrappers.vfa import vfa_fit, show_error_maps
from osipi_dce_dsc_repo.utils.nb import download_osf, loadmat, make_error_map_gif

vfafile = "./data/vfadata_noisy.mat"
download_osf("https://osf.io/3hwtc/download", vfafile)
vfadata = loadmat(vfafile)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mosipi_dce_dsc_repo[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnb[39;00m [38;5;28;01mimport[39;00m download_osf, loadmat, make_error_map_gif
[1;32m      4[0m vfafile [38;5;241m=[39m [38;5;124m"[39m[38;5;124m./data/vfadata_noisy.mat[39m[38;5;124m"[39m
[0;32m----> 5[0m [43mdownload_osf[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mhttps://osf.io/3hwtc/download[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mvfafile[49m[43m)[49m
[1;32m      6[0m vfadata [38;5;241m=[39m loadmat(vfafile)

File [0;32m/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/osipi_dce_dsc_repo/utils/nb.py:19[0m, in [0;36mdownload_osf[0;34m(url, file, overwrite)[0m
[1;32m     17[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124m  Skipping: [39m[38;5;132;01m{[39;00mfile[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m     18[0m     [38;5;28;01mreturn[39;00m
[0;32m---> 19[0m [43murllib[49m[38;5;241;43m.[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43murlretrieve[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mfile[49m[43m)[49m
[1;32m     20[0m [38;5;28;01mreturn[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/urllib/request.py:257[0m, in [0;36murlretrieve[0;34m(url, filename, reporthook, data)[0m
[1;32m    255[0m [38;5;66;03m# Handle temporary file setup.[39;00m
[1;32m    256[0m [38;5;28;01mif[39;00m filename:
[0;32m--> 257[0m     tfp [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mwb[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m    258[0m [38;5;28;01melse[39;00m:
[1;32m    259[0m     tfp [38;5;241m=[39m tempfile[38;5;241m.[39mNamedTemporaryFile(delete[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './data/vfadata_noisy.mat'
FileNotFoundError: [Errno 2] No such file or directory: './data/vfadata_noisy.mat'

